#!/usr/bin/env python3
"""Generate a multi-day EIT EPG for `tsp -P eitinject`.

Why this exists: the hand-written EPG in `eit-epg.xml` carries one day of events in a
single `<EIT type="pf">` element, and `eitinject` honours that `type` — so it yields EIT
p/f and no schedule whatsoever. Schedule is the interesting case for SI carriage, because
an EIT schedule sub-table is *sparse*: it declares a `last_section_number` covering its
whole 4-day range and transmits only the segment-boundary sections that hold events. A
receiver, or a MoQ importer, therefore cannot decide the sub-table is complete by counting
sections, and a full transmission cycle is 30 s at the ETSI TS 101 211 "later" rate.

`type` in TSDuck's EIT model is either `pf` or a uint4 selecting the schedule table
(`0` -> table_id 0x50 for EIT actual). `eitinject` re-segments the events it is given onto
the ETSI 3-hour segment grid, so this only has to emit the event list against the right
table and service triplet.

The event times must be anchored to the *stream's* TDT epoch, not to wall clock:
`eitinject` resynchronises on every TDT/TOT, and it drops events already in the past, so
an EPG anchored to today against a clip whose TDT says 2026-06-19 injects nothing.

Usage:
  make-eit-epg.py --out epg.xml [--days 8] [--services 1] [--epoch "2026-06-19 07:54:42"]
                  [--events-per-day 24] [--first-service-id 1]

  --days N          days of schedule to cover, from the epoch. 8 is the DVB planning
                    horizon and the size that makes the join cost worth measuring.
  --services N      distinct service_ids, each getting its own p/f and schedule
                    sub-tables — this is what multiplies the snapshot track count on an
                    MPTS.
  --descriptor-bytes N  pad each event's short-event text to roughly this many bytes, to
                    model a real EPG's descriptor weight rather than a terse synthetic one.
"""

import argparse
import datetime
import html


def event(event_id: int, start: datetime.datetime, hours: int, name: str, text: str) -> str:
	return f"""    <event event_id="{event_id}" start_time="{start:%Y-%m-%d %H:%M:%S}" duration="{hours:02d}:00:00"
           running_status="not-running" CA_mode="false">
      <short_event_descriptor language_code="eng">
        <event_name>{html.escape(name)}</event_name>
        <text>{html.escape(text)}</text>
      </short_event_descriptor>
    </event>"""


def main() -> None:
	ap = argparse.ArgumentParser()
	ap.add_argument("--out", required=True)
	ap.add_argument("--days", type=int, default=8)
	ap.add_argument("--services", type=int, default=1)
	ap.add_argument("--events-per-day", type=int, default=24)
	ap.add_argument("--epoch", default="2026-06-19 07:54:42", help="the source clip's TDT epoch")
	ap.add_argument("--first-service-id", type=int, default=1)
	ap.add_argument("--transport-stream-id", type=int, default=0)
	ap.add_argument("--original-network-id", type=int, default=0)
	ap.add_argument("--descriptor-bytes", type=int, default=120)
	args = ap.parse_args()

	epoch = datetime.datetime.strptime(args.epoch, "%Y-%m-%d %H:%M:%S")
	# Start the schedule on the hour after the epoch: eitinject drops past events, and an
	# event straddling the epoch belongs to p/f rather than to schedule.
	first = (epoch + datetime.timedelta(hours=1)).replace(minute=0, second=0, microsecond=0)
	slot = max(1, 24 // args.events_per_day)

	out = ['<?xml version="1.0" encoding="UTF-8"?>']
	out.append("<!-- Generated by make-eit-epg.py; do not edit by hand. -->")
	out.append("<tsduck>")

	for s in range(args.services):
		sid = args.first_service_id + s
		triplet = (
			f'service_id="{sid}" transport_stream_id="{args.transport_stream_id}" '
			f'original_network_id="{args.original_network_id}"'
		)

		# p/f: the event running at the epoch, and the one after it. Present must start
		# before the epoch or the table is empty for a receiver tuning at t=0.
		present = epoch.replace(minute=0, second=0, microsecond=0)
		pf = [
			event(1000 + s * 1000, present, 1, f"Service {sid} Now", "The present event."),
			event(1001 + s * 1000, first, 1, f"Service {sid} Next", "The following event."),
		]
		out.append(f'  <EIT type="pf" actual="true" version="1" current="true" {triplet}>')
		out.extend(pf)
		out.append("  </EIT>")

		# Schedule. One element per 4-day table range, which is how ETSI EN 300 468 splits
		# EIT schedule across table_ids (0x50 covers days 0-3, 0x51 days 4-7, ...).
		for table in range((args.days + 3) // 4):
			events = []
			eid = 2000 + s * 1000 + table * 300
			day_lo, day_hi = table * 4, min(args.days, table * 4 + 4)
			for day in range(day_lo, day_hi):
				for hour in range(0, 24, slot):
					start = first + datetime.timedelta(days=day, hours=hour)
					if start <= epoch:
						continue
					text = f"Synthetic schedule event for service {sid}, day {day}, hour {hour}. "
					events.append(
						event(
							eid,
							start,
							slot,
							f"S{sid} D{day} H{hour:02d}",
							(text * (args.descriptor_bytes // len(text) + 1))[: args.descriptor_bytes],
						)
					)
					eid += 1
			if not events:
				continue
			out.append(f'  <EIT type="{table}" actual="true" version="1" current="true" {triplet}>')
			out.extend(events)
			out.append("  </EIT>")

	out.append("</tsduck>")
	with open(args.out, "w") as fh:
		fh.write("\n".join(out) + "\n")

	tables = (args.days + 3) // 4
	print(f"wrote {args.out}")
	print(f"  services={args.services} days={args.days} events/day={args.events_per_day}")
	print(f"  schedule tables per service={tables} (table_id 0x50..0x{0x50 + tables - 1:02X})")


if __name__ == "__main__":
	main()
