#!/usr/bin/env python3
"""Can two independent egress processes of one broadcast be merged by an ST 2022-7 receiver?

A seamless-protection receiver merges a redundant pair by matching sequence numbers and taking
whichever copy arrives first. That only works if the two legs are *byte-identical* for the same
media: one differing octet and the merge either picks a corrupt packet or has to fall back to
resynchronising, which is the outage the pair exists to prevent. The property is therefore not
"both legs are valid streams" — two individually perfect streams make a useless pair — but "the
legs agree octet for octet once aligned".

This grades that. It takes two captures of the same broadcast from two processes that shared
nothing but the source, aligns them on media content rather than on position (they start at
different points), and compares the packets that follow.

Alignment is on a payload needle rather than on PCR or on packet index, because the values a
process mints for itself are exactly what is under test: aligning on one would assume the answer.
The needle is a run of payload octets from a PES packet, which is source media and cannot have
been regenerated by either process.

Differences are classified by field so the result names a mechanism rather than a percentage:

  cc        continuity counter (byte 3, low nibble) — per-process counter state
  pcr       the six PCR octets in the adaptation field — a regenerated clock
  pid       a different PID at the same offset — interleave or null placement diverged
  afield    other adaptation-field octets — stuffing length, flags
  payload   the media itself differs — the serious one

  ts-pair-diff.py <a.ts> <b.ts> [--window N] [--skip N]
"""
import sys

TS = 188
SYNC = 0x47


def load(path):
    with open(path, 'rb') as f:
        data = f.read()
    off = 0
    for i in range(TS):
        if all(data[i + k * TS] == SYNC for k in range(40) if i + k * TS < len(data)):
            off = i
            break
    n = (len(data) - off) // TS
    return data, off, n


def pkt(data, off, i):
    return data[off + i * TS: off + (i + 1) * TS]


def pid_of(p):
    return ((p[1] & 0x1F) << 8) | p[2]


def find_needle(data_a, off_a, n_a, data_b, off_b, skip):
    """A payload run from A that occurs exactly once in B, as a packet index into each.

    Also returns whether the run sits at the same offset within its packet in both. It usually
    will, and when it does not the two muxes placed the same media differently, which the
    field comparison then reports as a payload difference rather than hiding it.
    """
    for i in range(skip, min(n_a - 1, skip + 4000)):
        p = pkt(data_a, off_a, i)
        pid = pid_of(p)
        if pid in (0x1FFF, 0x0000, 0x0011, 0x0010) or not (p[3] & 0x10):
            continue                                    # null, PSI, or no payload
        af = p[4] + 1 if (p[3] & 0x20) else 0
        body = p[4 + af:]
        if len(body) < 48:
            continue
        needle = body[:48]
        if needle.count(needle[0:1]) > 40:              # a run of one octet is not distinctive
            continue
        first = data_b.find(needle)
        if first < 0 or data_b.find(needle, first + 1) >= 0:
            continue                                    # absent, or not unique
        k = (first - off_b) // TS
        if k < 0 or k >= (len(data_b) - off_b) // TS:
            continue
        aligned = ((first - off_b) % TS) == (4 + af)
        return i, k, aligned
    return None, None, None


def classify(a, b):
    """Which fields of two same-position packets differ."""
    out = set()
    if a[1:3] != b[1:3] or (a[0] != b[0]):
        out.add('pid')
        return out                                      # different packets; no field compare
    if (a[3] & 0x0F) != (b[3] & 0x0F):
        out.add('cc')
    if (a[3] & 0x30) != (b[3] & 0x30):
        out.add('afield')
    has_af = (a[3] & 0x20) and (b[3] & 0x20) and a[4] and b[4]
    if has_af and (a[5] & 0x10) and (b[5] & 0x10):
        if a[6:12] != b[6:12]:
            out.add('pcr')
    la = a[4] + 1 if (a[3] & 0x20) else 0
    lb = b[4] + 1 if (b[3] & 0x20) else 0
    if la != lb:
        out.add('afield')
    else:
        af_a, af_b = a[4:4 + la], b[4:4 + lb]
        if la and af_a != af_b:
            # The PCR occupies adaptation-field octets 2..8 and is reported on its own, so mask
            # it out here; whatever is left is a genuine adaptation-field difference.
            ma = af_a[:2] + af_a[8:] if la >= 8 else af_a
            mb = af_b[:2] + af_b[8:] if lb >= 8 else af_b
            if ma != mb:
                out.add('afield')
        if a[4 + la:] != b[4 + lb:]:
            out.add('payload')
    return out


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    opts = {a.split('=')[0]: a.split('=')[1] for a in sys.argv[1:] if '=' in a and a.startswith('--')}
    if len(args) < 2:
        print(__doc__)
        return 2
    window = int(opts.get('--window', 20000))
    skip = int(opts.get('--skip', 2000))

    da, oa, na = load(args[0])
    db, ob, nb = load(args[1])
    print(f"A {args[0]}: {na:,} packets")
    print(f"B {args[1]}: {nb:,} packets")

    ia, ib, aligned = find_needle(da, oa, na, db, ob, skip)
    if ia is None:
        print("\nNO COMMON MEDIA FOUND — the two captures share no unique payload run.")
        print("Either they carry different content, or every candidate needle recurred.")
        return 1
    print(f"\naligned on a 48-octet payload run: A packet {ia:,} == B packet {ib:,}")
    if not aligned:
        print("  note: the run sits at a different offset within its packet in each capture,")
        print("  so the two muxes packed the same media differently.")

    n = min(na - ia, nb - ib, window)
    same = 0
    fields = {}
    first_diff = None
    for k in range(n):
        a, b = pkt(da, oa, ia + k), pkt(db, ob, ib + k)
        if a == b:
            same += 1
            continue
        if first_diff is None:
            first_diff = k
        for f in classify(a, b):
            fields[f] = fields.get(f, 0) + 1

    print(f"compared {n:,} packets from the alignment point\n")
    print(f"  identical:  {same:,} of {n:,}  ({same / n * 100:.2f} %)")
    print(f"  differing:  {n - same:,}")
    if first_diff is not None:
        print(f"  first difference at packet {first_diff:,} after the anchor")
    print()
    if not fields:
        print("  VERDICT: byte-identical over the window. The pair is mergeable.")
        return 0
    print("  differing packets by field (a packet can differ in more than one):")
    for f in ('pid', 'cc', 'pcr', 'afield', 'payload'):
        if f in fields:
            print(f"    {f:<8} {fields[f]:>8,}  ({fields[f] / n * 100:5.2f} % of window)")
    print()
    print("  VERDICT: not byte-identical. An ST 2022-7 receiver cannot merge this pair;")
    print("  the fields above name what each process minted for itself.")
    return 1


if __name__ == '__main__':
    sys.exit(main())
